### PR TITLE
Added findtext and xpath

### PR DESCRIPTION
**Pull request by dispread**
I dont know why they werent already there so I added them.

Peace out

### CODE REVIEW

**Comment by dispread** [comment]
Guess i found out

**Comment by dispread** [comment]
I swear I'm not retarded, just tired

**Comment by abelcheung** [comment]
@dispread No sweat, please do it at your own pace. I'll check again tomorrow, in case you have additional commits related to this change.

**Comment by abelcheung** [comment]
@dispread  If these changes are all you intended to submit, then they are not needed. As I said before, if the methods don't exist in `HtmlElement`, the corresponding definition of `findtext()` and `xpath()` in its superclasses (`etree._Element` in this case) would be picked up.

Feel free to reopen this PR if you have other changes in mind.

**Comment by dispread** [comment]
@abelcheung 
Just out of curiosity, what IDE are you testing this on? I am using Pycharm and it doesn't seem to recognize the inherited methods hence my commits. Even on my branch it defaults to showing the autogenerated stubs, which is better than original (no hint on inherited Html element methods).
Is there something I'm missing?

Thanks in advance 👍

**Comment by abelcheung** [comment]
I see. I'm using vscode with pylance extension, and everything just works automatically. If pycharm really needs a manual override of methods in order to show up, that could indicate either oversight of setting or a missing feature. Even in terms of pure stub itself (disregarding any IDE support), this manual override shouldn't be needed at all. Guess I need to spend some time to get #8 going then.

**Comment by abelcheung** [comment]
I can reproduce the problem you have faced with a default installation of Pycharm 2024.1. The autocompletion popup manages to show `ElementBase.__init__()` (The direct superclass of `HtmlElement`), but doesn't go beyond that.

[This PyCharm issue](https://youtrack.jetbrains.com/issue/PY-21794/Stub-files-from-parent-class-not-used-for-derived-child-classes) seems to fit the description we are facing, but it's more than 7 years ago, and (still) in dead silence.

Will try to continue investigating later on, for now perhaps you can also try out if vscode works fine for you.

**Pull request closed without merging**
